### ISSUE TITLE
Subset sum = zero

### ISSUE THREAD

**Issue by Loucif-Fouad** [cambusa/rygauge#1]
I'm testing your great component to search for a subset with sum equals to zero but it doesn't find it in the first try.

**Comment by cambusa** [comment]
You are right!
I fixed the bug.
Thanks for the report.
Rudy

**Comment by Loucif-Fouad** [comment]
> You are right!
> I fixed the bug.
> Thanks for the report.
> Rudy

WOW it was very fast thanks a lot.
